import type { Team } from './types';

export const teams: Team[] = [
  {
    id: 1,
    name: 'Arsenal',
    shortName: 'Arsenal',
    primaryColor: '#EF0107',
    secondaryColor: null,
  },
  {
    id: 2,
    name: 'Aston Villa',
    shortName: 'Aston Villa',
    primaryColor: '#670E36',
    secondaryColor: '#95BFE5',
  },
  {
    id: 3,
    name: 'AFC Bournemouth',
    shortName: 'Bournemouth',
    primaryColor: '#DA291C',
    secondaryColor: null,
  },
  {
    id: 4,
    name: 'Brentford',
    shortName: 'Brentford',
    primaryColor: '#fd0000',
    secondaryColor: null,
  },
  {
    id: 5,
    name: 'Brighton',
    shortName: 'Brighton',
    primaryColor: '#0057B8',
    secondaryColor: null,
  },
  {
    id: 6,
    name: 'Burnley',
    shortName: 'Burnley',
    primaryColor: '#70193d',
    secondaryColor: null,
  },
  {
    id: 7,
    name: 'Chelsea',
    shortName: 'Chelsea',
    primaryColor: '#1B458F',
    secondaryColor: null,
  },
  {
    id: 8,
    name: 'Crystal Palace',
    shortName: 'C. Palace',
    primaryColor: '#003399',
    secondaryColor: null,
  },
  {
    id: 9,
    name: 'Everton',
    shortName: 'Everton',
    primaryColor: '#003399',
    secondaryColor: null,
  },
  {
    id: 10,
    name: 'Fulham',
    shortName: 'Fulham',
    primaryColor: '#000000',
    secondaryColor: null,
  },
  {
    id: 11,
    name: 'Liverpool',
    shortName: 'Liverpool',
    primaryColor: '#d3171e',
    secondaryColor: null,
  },
  {
    id: 12,
    name: 'Luton Town',
    shortName: 'Luton',
    primaryColor: '#fc5001',
    secondaryColor: null,
  },
  {
    id: 13,
    name: 'Manchester City',
    shortName: 'Man City',
    primaryColor: '#6CABDD',
    secondaryColor: null,
  },
  {
    id: 14,
    name: 'Manchester United',
    shortName: 'Man Utd',
    primaryColor: '#DA291C',
    secondaryColor: null,
  },
  {
    id: 15,
    name: 'Newcastle United',
    shortName: 'Newcastle',
    primaryColor: '#000000',
    secondaryColor: null,
  },
  {
    id: 16,
    name: 'Nottingham Forest',
    shortName: 'Notts Forest',
    primaryColor: '#DC0202',
    secondaryColor: null,
  },
  {
    id: 17,
    name: 'Sheffield United',
    shortName: 'Sheff Utd',
    primaryColor: '#F12228',
    secondaryColor: null,
  },
  {
    id: 18,
    name: 'Tottenham Hotspur',
    shortName: 'Tottenham',
    primaryColor: '#0f204b',
    secondaryColor: null,
  },
  {
    id: 19,
    name: 'West Ham United',
    shortName: 'West Ham',
    primaryColor: '#540d1a',
    secondaryColor: null,
  },
  {
    id: 20,
    name: 'Wolverhampton Wanderers',
    shortName: 'Wolves',
    primaryColor: '#FC891C',
    secondaryColor: null,
  },
];
