import type { Actions, PageServerLoad } from './$types';
import { getServerSession, getSupabase } from '@supabase/auth-helpers-sveltekit';
import type { Fixture } from '@lib/types';
import { supabaseClient } from '@lib/db';
import { fail, redirect } from '@sveltejs/kit';
import { formatFixtures } from '@lib/util/fixture';
import { getActiveGameweek } from '@lib/util/gameweek';

export const actions: Actions = {
	select: async (event) => {
		const selection = event.url.searchParams.get('selection');
		const fixture = event.url.searchParams.get('fixture');
		const gameweek = event.url.searchParams.get('gameweek');

		const { session, supabaseClient } = await getSupabase(event);
		if (!session) {
			throw redirect(303, '/login');
		}

		const { data: selections } = await supabaseClient
			.from('Selections')
			.select()
			.eq('selector', session?.user.id);

		const existingGameweekSelection = selections?.find(
			(selection) => selection?.gameweek === Number(gameweek)
		);

		if (existingGameweekSelection?.id) {
			console.log('overwriting selection');
			const { data, error } = await supabaseClient
				.from('Selections')
				.update({
					selection: selection,
					selector: session?.user?.id,
					fixture: fixture,
					gameweek: gameweek
				})
				.eq('id', existingGameweekSelection?.id);

			if (error) {
				console.log(error);
				return fail(400, {
					message: 'We were unable to process your selection.'
				});
			}
		} else {
			const { data, error } = await supabaseClient.from('Selections').insert({
				selection: selection,
				selector: session?.user?.id,
				fixture: fixture,
				gameweek: gameweek
			});

			if (error) {
				console.log(error);
				return fail(400, {
					message: 'We were unable to process your selection.'
				});
			}
		}
	}
};

export const load = (async (event: any) => {
	const { activeGameweek } = await event.parent();
	const { params, fetch } = event;

	const session = await getServerSession(event);

	const res = await fetch(
		`https://fantasy.premierleague.com/api/fixtures?event=${params.gameweek}`,
		{
			headers: {
				'Access-Control-Allow-Origin': 'https://fantasy.premierleague.com'
			}
		}
	);

	if (!res.ok) {
		throw fail(500, {
			message: 'Unable to fetch fixtures'
		});
	}

	const fixtures = await res.json();
	const formattedFixtures = formatFixtures(fixtures);

	const { data, error } = await supabaseClient
		.from('Selections')
		.select()
		.eq('selector', session?.user?.id);

	const gameweekFixtures = formattedFixtures.filter(
		(fixture: Fixture) => fixture.event === Number(params.gameweek)
	);

	return {
		selections: data ?? [],
		activeGameweek: activeGameweek,
		formattedFixtures,
		gameweek: {
			event: Number(params.gameweek),
			fixtures: gameweekFixtures as Array<Fixture>
		}
	};
}) satisfies PageServerLoad;

export const config = {
	isr: {
		// Expiration time (in seconds) before the cached asset will be re-generated by invoking the Serverless Function.
		// Setting the value to `false` means it will never expire.
		expiration: 60
	}
};
